from voluptuous import Schema, Required, PREVENT_EXTRA

openapi: 3.0.3
info:
  title: SKKS API - Auth
  version: '2.0'
  description: |
    Документация API проекта СККС
    Авторизация в системе и получения токена
servers:
  - url: 'https://dev0skks.etalongroup.com'
paths:
  /auth/login:
    summary: Авторизация
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  description: Адрес эл. почты
                  type: string
                password:
                  description: Пароль
                  type: string
              required:
                - id
        required: true
      responses:
        '400':
          description: Ошибка авторизации
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    default: false
                  error:
                    type: string
                    description: |
                      Код ошибки
                      - `user_invalid_argument_email` - некорретный e-mail
                      - `user_invalid_argument_password`
                      - `user_not_found`
                    enum:
                      - user_invalid_argument_email
                      - user_invalid_argument_password
                      - user_not_found
                    example: user_not_found
                required:
                  - ok
                  - error
        default:
          description: После успешной авторизации получаем токен
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    default: true
                  result:
                    type: object
                    properties:
                      user_id:
                        type: integer
                      token_type:
                        type: string
                        default: Bearer
                      access_token:
                        type: string
                      expires_in:
                        type: integer
                required:
                  - user_id
                  - token_type
                  - access_token
                  - expires_in
  /api/v2/Auth/restore.password:
    summary: >-
      Восстановление пароля пользователя - Шаг 1 - Отправка письма для
      восстановления пароля
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  description: 'Адрес эл. почты пользователя, указанный при регистрации'
                  type: string
                  format: email
              required:
                - email
        required: true
      responses:
        '200':
          description: Письмо для восстановления пароля отправлено на указанный e-mail
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    default: true
                  result:
                    type: string
                    example: true
                required:
                  - ok
                  - result
        '400':
          description: Ошибка
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    default: false
                  error:
                    type: string
                    description: |
                      Код ошибки
                      - `user_invalid_argument_email` - некорректный e-mail
                      - `user_not_found` - пользователь не найден
                    enum:
                      - user_invalid_argument_email
                      - user_not_found
                    example: user_not_found
                required:
                  - ok
                  - error
  /api/v2/Auth/reset.password:
    summary: >-
      Восстановление пароля пользователя - Шаг 2 - Сброс пароля по ссылке из
      письма
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                hash:
                  description: Хэш из ссылки для восстановления пароля
                  type: string
                  maxLength: 32
                new_password:
                  description: Новый пароль
                  type: string
                  maxLength: 255
              required:
                - hash
                - new_password
        required: true
      responses:
        '200':
          description: Новый пароль пользователя сохранён
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    default: true
                  result:
                    type: string
                    example: true
                required:
                  - ok
        '400':
          description: Ошибка
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    default: false
                  error:
                    type: string
                    description: Код ошибки
                    example: error_text
                required:
                  - ok
                  - error
